framework:
    messenger:
        transports:
            user_message_transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    # librdkafka configuration options are available here
                    # https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md
                    metadata.broker.list: '%env(KAFKA_BROKERS)%'
                    security.protocol: 'plaintext' # plaintext, ssl, sasl_plaintext, sasl_ssl
                    group.id: 'user-message-id' # consumer group id
                    auto.offset.reset: 'earliest' # 'earliest': start from the beginning
                    enable.partition.eof: 'true' # Emit EOF event when reaching the end of a partition
                    #allow.auto.create.topics: true # Allow automatic topic creation on the broker
                    #ssl.certificate.location: ''
                    message.send.max.retries: 5 # How many times to retry sending a failing Message

                    # (not required, default false) if true then RD_KAFKA_MSG_F_BLOCK will apply
                    # @see https://github.com/arnaud-lb/php-rdkafka/blob/6.x/README.md#producing-messages
                    producer_message_flags_block: false

                    # (not required, default -1 unassigned) the partition id
                    # @see https://github.com/arnaud-lb/php-rdkafka/blob/6.x/README.md#producing-messages
                    #producer_partition_id_assignment: 0
                    #producer_poll_timeout_ms: 10 # (not required, default 0)
                    #producer_flush_timeout_ms: 20000 # (not required, default 10000)
                    producer_topic: 'user_message_topic'

                    #consumer_consume_timeout_ms: 30000 # (not required, default 10000)
                    consumer_topics:
                        - 'user_message_topic'
            user_message_transport_1:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    metadata.broker.list: '%env(KAFKA_BROKERS)%'
                    security.protocol: 'plaintext'
                    group.id: 'user-message-id-1'
                    auto.offset.reset: 'earliest'
                    enable.partition.eof: 'true'
                    message.send.max.retries: 5
                    producer_message_flags_block: false
                    producer_topic: 'user_message_topic'
                    consumer_topics:
                        - 'user_message_topic'
            user_message_transport_2:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    metadata.broker.list: '%env(KAFKA_BROKERS)%'
                    security.protocol: 'plaintext'
                    group.id: 'user-message-id-2'
                    auto.offset.reset: 'earliest'
                    enable.partition.eof: 'true'
                    message.send.max.retries: 5
                    producer_message_flags_block: false
                    producer_topic: 'user_message_topic'
                    consumer_topics:
                        - 'user_message_topic'
            user_message_transport_3:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    metadata.broker.list: '%env(KAFKA_BROKERS)%'
                    security.protocol: 'plaintext'
                    group.id: 'user-message-id-3'
                    auto.offset.reset: 'earliest'
                    enable.partition.eof: 'true'
                    message.send.max.retries: 5
                    producer_message_flags_block: false
                    producer_topic: 'user_message_topic'
                    consumer_topics:
                        - 'user_message_topic'

        routing:
            'App\Messenger\Message\UserMessage': user_message_transport

        serializer:
            default_serializer: messenger.transport.symfony_serializer

when@test:
    framework:
        messenger:
            transports:
                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
                order_transport: 'in-memory://'
                invoice_transport: 'in-memory://'
